from .input import Input
from .switch import Switch
from .redirect import Redirect
from .click import Click
from .slide import Slide
from .select import Select
from .get import Get
from .window import Window
from .scroll import Scroll
from .alert import Alert
